### ISSUE TITLE
Android启动在线客户 2s左右闪退

### ISSUE THREAD

**Issue by yhrun** [Meiqia/MeiqiaSDK-Android#152]
java.lang.NoClassDefFoundError: com.meiqia.core.cp
                                                                      at com.meiqia.core.MeiQiaService.a(Unknown Source)
                                                                      at com.meiqia.core.MeiQiaService.onStartCommand(Unknown Source)
                                                                      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4062)
                                                                      at android.app.ActivityThread.access$2400(ActivityThread.java:221)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1897)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Process: com.shirble.retailer.app, PID: 22938
                                                                          java.lang.NoClassDefFoundError: com.meiqia.core.cp
                                                                              at com.meiqia.core.MeiQiaService.a(Unknown Source)
                                                                              at com.meiqia.core.MeiQiaService.onStartCommand(Unknown Source)
                                                                              at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4062)
                                                                              at android.app.ActivityThread.access$2400(ActivityThread.java:221)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1897)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:158)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ksxkq** [comment]
okhttp 需要 3.5.0 以上版本
