### ISSUE TITLE
5.0	vivo	vivo X5Pro D 打开数据库崩溃

### ISSUE THREAD

**Issue by lguipeng** [Meiqia/MeiqiaSDK-Android#157]
sdk 版本 3.4.0

android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:214)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:198)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:836)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1252)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at com.meiqia.core.bz.c(Unknown Source)
	at com.meiqia.core.bz.a(Unknown Source)
	at com.meiqia.core.bz.a(Unknown Source)
	at com.meiqia.core.d$a.a(Unknown Source)
	at com.meiqia.core.da.a(Unknown Source)
	at com.meiqia.core.du.onResponse(Unknown Source)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by ksxkq** [comment]
有复现步骤吗？如果，把步骤发一下，然后我这边再看看
