### ISSUE TITLE
SQLiteFullException:android.database.sqlite.SQLiteFullException: database or disk is full (code 13)

### ISSUE THREAD

**Issue by luzhongxu** [Meiqia/MeiqiaSDK-Android#195]
#0. Crashed: OkHttp Dispatcher
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
       at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:262)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.meiqia.core.cc.b(Unknown Source)
       at com.meiqia.core.cc.a(Unknown Source)
       at com.meiqia.core.cc.a(Unknown Source)
       at com.meiqia.core.d$a.onSuccess(Unknown Source)
       at com.meiqia.core.dd.a(Unknown Source)
       at com.meiqia.core.dy.onResponse(Unknown Source)
       at okhttp3.RealCall$AsyncCall.execute(Paramount:153)
       at okhttp3.internal.NamedRunnable.run(Paramount:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by ksxkq** [comment]
什么手机，系统版本多少

**Comment by luzhongxu** [comment]
> 什么手机，系统版本多少

![wechatimg934](https://user-images.githubusercontent.com/4519354/51581251-3f113a00-1f02-11e9-8851-ac7035acc012.png)

**Comment by ksxkq** [comment]
看起来就是存储满了，我也不好判断。操作系统是 5、6，应该是比较旧的手机，还是比较有可能的
