### ISSUE TITLE
java.lang.IllegalStateException - 3.4.6

### ISSUE THREAD

**Issue by Yunfeng1u** [Meiqia/MeiqiaSDK-Android#200]
```
java.lang.IllegalStateException: Not allowed to start service Intent { act=ACTION_OPEN_SOCKET cmp=com.wannar.wannar_adroid2/com.meiqia.core.MeiQiaService }: app is in background uid UidRecord{b3281ca u0a225 TPSL bg:+30m51s605ms idle procs:1 seq(0,0,0)} 	
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577) 	
at android.app.ContextImpl.startService(ContextImpl.java:1532) 	
at android.content.ContextWrapper.startService(ContextWrapper.java:664) 	
at com.meiqia.core.bv.a(Unknown Source:12) 	
at com.meiqia.core.a.f(Unknown Source:9) 	
at com.meiqia.meiqiasdk.controller.a.d(SourceFile:282) 	
at com.meiqia.meiqiasdk.activity.MQConversationActivity.onStart(SourceFile:248) 	
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391) 	
at android.app.Activity.performStart(Activity.java:7165) 	
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975) 	
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180) 	
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165) 	
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) 	
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 	
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 	
at android.os.Handler.dispatchMessage(Handler.java:106) 	
at android.os.Looper.loop(Looper.java:193) 	
at android.app.ActivityThread.main(ActivityThread.java:6718) 	
at java.lang.reflect.Method.invoke(Native Method) 	
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 	
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by ksxkq** [comment]
升级到最新版，然后 App 后台的时候，关闭美洽服务
