### ISSUE TITLE
后台报错，请问是什么问题？

### ISSUE THREAD

**Issue by LinhaiGu** [Meiqia/MeiqiaSDK-Android#206]
java.lang.ClassCastException: com.meiqia.meiqiasdk.chatitem.MQClientItem cannot be cast to com.meiqia.meiqiasdk.chatitem.MQTimeItem
    at com.meiqia.meiqiasdk.util.MQChatAdapter.getView(MQChatAdapter.java:156)
    at android.widget.AbsListView.obtainView(AbsListView.java:2445)
    at android.widget.HwAbsListView.obtainView(HwAbsListView.java:944)
    at android.widget.ListView.makeAndAddView(ListView.java:2078)
    at android.widget.ListView.fillUp(ListView.java:834)
    at android.widget.ListView.layoutChildren(ListView.java:1811)
    at android.widget.AbsListView.onLayout(AbsListView.java:2243)
    at android.widget.HwAbsListView.onLayout(HwAbsListView.java:351)

**Comment by ksxkq** [comment]
这个问题能复现吗？
