### ISSUE TITLE
崩溃java.lang.VerifyErro

### ISSUE THREAD

**Issue by victorfan336** [Meiqia/MeiqiaSDK-Android#270]
崩溃日志：
java.lang.VerifyError: Verifier rejected class com.meiqia.core.m0: void com.meiqia.core.m0.<init>(android.content.Context) failed to verify: void com.meiqia.core.m0.<init>(android.content.Context): [0xB] cannot access instance field okhttp3.OkHttpClient com.meiqia.core.m0.c from object of type Reference: okhttp3.OkHttpClient (declaration of 'com.meiqia.core.m0' appears in /data/app/com.eybond.smartvalue-w6WUzoEg_JczUDdNbKIbtA==/base.apk!classes19.dex)
                                                                                                    	at com.meiqia.core.m0.a(Unknown Source:0)
                                                                                                    	at com.meiqia.core.MQManager.onConversationOpen(Unknown Source:7)
                                                                                                    	at com.meiqia.meiqiasdk.controller.ControllerImpl.onConversationOpen(ControllerImpl.java:314)
                                                                                                    	at com.meiqia.meiqiasdk.activity.MQConversationActivity.onCreate(MQConversationActivity.java:234)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8214)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8202)

我们项目中用的是okhttp 4.10.0，但是我在demo中单独引用okhttp 4.10.0，demo是不会报错的。
报错的代码是：
Intent intent = new MQIntentBuilder(getContext()).build();
        startActivity(intent);
一执行这两行代码就崩溃。
按照android SDK 步骤接入的，SDK初始化是成功的。
麻烦解决下，谢谢

**Comment by ksxkq** [comment]
试试 v4.0.18
